# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Masatoshi Nishiguchi
email: masatoshi.nishiguchi@udc.edu
description: Masatoshi Nishiguchi's blog
baseurl: "/my_jekyll_site"              # the subpath of your site, e.g. /blog
url:     "http://mnishiguchi.github.io" # the base hostname & protocol for your site

twitter_username: mnishiguchiDC
github_username:  mnishiguchi

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
